spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/department_db?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      use_sql_comments: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  boot:
    message: 'Hello, Department Service Spring Cloud Bus Demo'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
        
management:
  endpoints:
    web:
      exposure:
        include: '*'

        



